### PR TITLE
Support GHC 9.4

### PR DESCRIPTION
**Pull request by robx**
- cleans up CI GHC versions (this could be skipped if desired)
- updates bounds on base and ghc-prim to allow building with GHC 9.4
- adds GHC 9.4 to CI

### CODE REVIEW

**Comment by robx** [comment]
This should be good enough to pass CI (fingers crossed), but isn't quite ready to merge since we'd want a release of async with https://github.com/simonmar/async/pull/134 first.

**Comment by robx** [comment]
Could I get CI approval here, and/or a review?

**Comment by robx** [comment]
@adamwespiser could you have a look at this?

**Comment by adamwespiser** [comment]
@robx I'm on it. I approved the runs. Once they pass I'll merge and cut a release. Thank you for your patience w/ this.

**Review by adamwespiser — APPROVED** [review]
LGTM. Thank you for your contribution.

**Comment by adamwespiser** [comment]
I merged this commit in the following PR: https://github.com/protolude/protolude/pull/142

(one of the actions needed to be updated)

**Comment by adamwespiser** [comment]
@robx https://hackage.haskell.org/package/protolude-0.3.3

**Pull request closed without merging**
