### PR TITLE
Make it build with ghc 9.8 (update deps only)

### PR DESCRIPTION
**Pull request by erikd**

### CODE REVIEW

**Comment by Vekhir** [comment]
@adamwespiser 
Is something blocking this PR adding support for GHC 9.8 to `protolude` from being merged?

**Comment by adamwespiser** [comment]
yes, a ton of the CI is broken, nix, stack.

If you are confident this works, I can merge it.

**Comment by Vekhir** [comment]
Using `configurator-pq` and `postgrest` as proxies, I'm confident that `protolude` is compatible with the version bounds contained in this PR.
Please make a new Hackage release once it's merged.

**Comment by adamwespiser** [comment]
@Vekhir https://hackage.haskell.org/package/protolude-0.3.4

**Pull request merged**
