### PR TITLE
Allow bytestring-0.11

### PR DESCRIPTION
**Pull request by Bodigrim**

### CODE REVIEW

**Comment by Bodigrim** [comment]
@sdiehl ping

**Comment by Bodigrim** [comment]
@adamwespiser ping

**Comment by adamwespiser** [comment]
I'll take a look, first I need to fix the Github/Travis actions in another PR

**Comment by Bodigrim** [comment]
@adamwespiser what is blocking this?

**Comment by adamwespiser** [comment]
I don't have permission to merge the PR which replaces the broken tests, I'll ping Stephen and see if we can get unblocked...

**Comment by Bodigrim** [comment]
Sorry, but I'm afraid I'd like to get this out of my radar sooner than later. Closing.

**Pull request closed without merging**
