### PR TITLE
GHC 8.6.1 support

### PR DESCRIPTION
**Pull request by andrevdm**
- Bounds changes for base, containers and stm
 - stack lts 12.* tests
 - works with stack 8.6.1 nightly
    stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
 - works with cabal new-build

### CODE REVIEW

**Comment by andrevdm** [comment]
There was a comment for 0.2.3 so I've assumed this would be version 0.2.4

**Comment by sdiehl** [comment]
Beat me to this by about 10 minutes. The last thing to update is just the `travis.yml` file to work with the cabal new-build for GHC 8.6.1.

**Comment by andrevdm** [comment]
I've pushed what I think is required to travis.yaml. Hopefully I'm not missing anything there

**Comment by sdiehl** [comment]
Rebased with my patch branch. I'll merge as soon as CI passes.

**Comment by andrevdm** [comment]
Are you going to upload to hackage as 0.2.4? 

I'm updating my local package bounds assuming that and everything is working locally now. I'm just not sure if there is a process you follow before uploading to stackage?

Thanks again

**Comment by sdiehl** [comment]
Indeed, I just made an announcement for anyone that wants to pull it from GitHub for testing. It's passing against all versions going back to GHC 7.6 so we should be all set for a new upload. After which I'll upload to Hackage and Stackage and it should land in the next LTS resolver.

**Comment by andrevdm** [comment]
Fantastic, thank you.

**Pull request merged**
