### PR TITLE
gcdInt' and gcdWord' are defined only with integer-gmp

### PR DESCRIPTION
**Pull request by mimi1vx**

### CODE REVIEW

**Comment by mimi1vx** [comment]
ping @adamwespiser , @sdiehl  told me you are new maintainer of protolude

**Comment by adamwespiser** [comment]
Sure thing!
There looks to be a CI build error, let me take a look to see what's going on...

**Comment by adamwespiser** [comment]
The Github Actions are broken, I'm updating them now. Should have a fix in relatively soon, and you'll be able to rebase/merge the changes in and pass the tests.

**Comment by mimi1vx** [comment]
@adamwespiser ping, any change?

**Comment by adamwespiser** [comment]
> @adamwespiser ping, any change?

yes, I've fixed 2/3 broken CI tests. The last broken test Travis, will need some more work but should be doable.

**Comment by felixonmars** [comment]
It's no longer present in base-4.15.0.0 even if integer-gmp is installed. Perhaps we need a version check here too?

**Comment by mimi1vx** [comment]
> It's no longer present in base-4.15.0.0 even if integer-gmp is installed. Perhaps we need a version check here too?

yes , GHC-9+ doesnt use integer-gmp anymore ... so why you have it installed ? ( but still it needs add  max version condition to `< 4.15`

**Comment by maksbotan** [comment]
Hi @sdiehl,

Now that's GHC 9 is in Stackage Nightly, what's the status of this PR? protolude is a dependency of quite a lot of packages, so would be nice for it to gain GHC 9 compatibility.

**Comment by adamwespiser** [comment]
@maksbotan Stephen gave me ownership over the repo, which is enough to fix up the failing CI tests and get this stuff in.

I'll need a few more hours to get the CI tests working, but after that this will go in.

**Pull request merged**
