### PR TITLE
Add total ConvertText alternative to Conv

### PR DESCRIPTION
**Pull request by seagreen**

### CODE REVIEW

**Comment by sdiehl** [comment]
This is nice because it preserves API comparability and is opt-in. 👍

**Comment by seagreen** [comment]
> This is nice because it preserves API comparability and is opt-in. ￼

Glad you like it. To be clear though it is a breaking change because of this line: https://github.com/protolude/protolude/pull/113/files#diff-09c50a38bb738937666bdca0897f9f46L44, is that OK?

Also CI is failing, but that's just due to hlint having suggestions for pre-existing code.

**Comment by seagreen** [comment]
Actually a double-breaking change because it also changes the type of `show`.

**Comment by sdiehl** [comment]
If we rename the exposed function `convertText` to `toS` then we can just have a nice drop in-replacement that is total, if we omit the default export of _either_ in `Protolude.hs` and make this module opt-in and then in the FAQ just say that if you want total ones import this module otherwise the old one which have the same interface but sans some instances. For existing code that's using toS then users just need to adjust their imports.

```haskell
import Protolude.Conv
import Protolude.ConvertText
```

The `show` export in `Protolude.hs` could use either because every show instance is obviously never going to have issues with total conversions.

**Comment by seagreen** [comment]
Pushed up a commit renaming `convertText` to `toS`.

I had the idea that if we still re-export `ConvertText` from `Protolude` that would lead to the maximum backwards-compatibility, since people who are only using its total variants won't have to change anything, not even adding a new import.

The cost is that if the user really does want `Protolude.Conv` they have to hide `toS` from `Protolude`, but that doesn't seem too serious.

How does that sound to you?

**Comment by sdiehl** [comment]
> The cost is that if the user really does want Protolude.Conv they have to hide toS from Protolude, but that doesn't seem to serious.

That seems like a sensible migration path. If anything everyone using the partial versions will now get a warning. 

I'll merge this branch into my 3.0 and this will become the new default. 👍

**Pull request merged**
